### ISSUE TITLE
Question: Where did you found FilledButton?

### ISSUE THREAD

**Issue by yayolius** [appintheair/react-native-buyscreen#1]
I looked into the documentation and i could not find it

**Comment by wannabehero** [comment]
@yayolius made it myself, here is the code: https://github.com/appintheair/react-native-buyscreen/blob/master/js/components/FilledButton.js

May by it's better to make a separate repo. Thanks!

**Comment by yayolius** [comment]
Hey, just so you know.
I tried to style the button just like you but adding the classic 3d with border-bottom, that one uses in CSS, but in React-Native the border does not follow the round property.
Thanks.
